# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
cloud:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

frontend:
  themes: !include_dir_merge_named themes

# MariaDb
recorder:
  db_url: !secret db_path

# Text to speech
tts:
  - platform: google_translate

lovelace:
  mode: yaml

# hacs:
#   theme: True

shelly:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Alarm control panel
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    arming_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

# # Alarm Triggers (Away)
# automation:
#   - alias: 'Trigger alarm while armed away'
#     trigger:
#       - platform: state
#         entity_id: binary_sensor.lv_sensor_motion
#         to: "Detected"
#       #more platforms
#     condition: 
#       - condition: state
#         entity_id: alarm_control_panel.home_alarm
#         state: armed_away
#     action:
#       service: alarm_control_panel.alarm_trigger
#       target:
#         entity_id: alarm_control_panel.home_alarm
    
#   - alias: 'Send notification when alarm is triggered'
#     trigger:
#       - platform: state
#         entity_id: alarm_control_panel.home_alarm
#         to: "triggered"
#     action:
#       - service: notify.notify
#         data:
#           message: "INTRUDER!  The alarm has been triggered."


media_player:
  # VizioTV - RedRoom
  - platform: vizio
    host: 192.168.86.122:9000
    access_token: !secret red_vizio_token
  
  # NVIDIA SHIELD - Red Room
  - platform: androidtv
    host: 192.168.86.221
    name: Android TV
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037

# Notifications: AndroidTV
notify:
- platform: nfandroidtv
  name: red_room
  host: 192.168.86.221

sensor:
  - platform: darksky
    api_key: !secret darksky
    forecast:
      - 0
    hourly_forecast:
      - 0
      - 1
    monitored_conditions:
      - summary
      - icon
      - temperature

switch:
  # Middle Light Red Room
  - platform: mqtt
    name: "Red Room 2"
    command_topic: "cmnd/switch02/POWER"
    state_topic: "stat/switch02/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
  # Back Light Red Room
  - platform: mqtt
    name: "Red Room 3"
    command_topic: "cmnd/switch03/POWER"
    state_topic: "stat/switch03/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"

light:
  - platform: mqtt
    name: "RRLED"
    command_topic: "cmnd/LED1/power"
    state_topic: "stat/LED1/POWER"
    rgb_state_topic: "stat/LED1/color"
    rgb_command_topic: "cmnd/LED1/color"
    brightness_state_topic: "stat/LED1/dimmer"
    brightness_command_topic: "cmnd/LED1/dimmer"
    retain: true

group:
  red_room:
    name: Red Room
    entities:
      - switch.red_room_2
      - switch.red_room_3