esphome:
  name: salt_sensor
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret ssid
  password: !secret wifi_pass

logger:

api:

ota:

sensor:
  - platform: ultrasonic
    id: salt_sensor
    trigger_pin: GPIO5
    echo_pin: GPIO4
    name: "Water Softener Level"
    update_interval: 10s
    filters:
      filter_out: nan
    timeout: 9m
  - platform: dht
    model: DHT11
    pin: GPIO14
    temperature:
      name: "Red Room Temperature"
    humidity:
      name: "Red Room Humidity"
    update_interval: 15s
web_server:
  port: 80